services:
#    jo_platform.example:
#        class: JO\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    jo_platform.antispam:
        class: JO\PlatformBundle\Antispam\JOAntispam
        arguments: [@mailer, %locale%, 50]